theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  summary:
    position: hero
  search:
    active: true  
  breadcrumb:
    position: hero-end
  logo:
    header: "/assets/images/logo.png"
    footer: "/assets/images/logo.png"  
  posts:
    default_image: true
    index:
      layout: grid
  pages:
    index:
      layout: list
  image_sizes:
    blocks:
      call_to_action:
        mobile:   375
        tablet:   500
        desktop:  1440
    sections:
      home:
        hero:
          mobile:   400
          tablet:   800
          desktop:  1440